#!/bin/sh

process="named"
logfile="/var/log/pguard.log

while(true)
do
  if [ ! `ps ax | pgrep $process` ]
  then
    /etc/rc.d/named start
    echo "`date` [RESTARTED] $process was crashed" >> $logfile
  fi

  sleep 5
done

